multitenancy_enabled: false

blocks_storage:
  backend: s3
  s3:
    endpoint: garage:3900
    region: us-east-1
    bucket_name: mimir
    access_key_id: ${GARAGE_ACCESS_KEY}
    secret_access_key: ${GARAGE_SECRET_KEY}
    insecure: true
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

server:
  http_listen_port: 9090
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1