services:
  loki:
    image: grafana/loki:3.7.1
    container_name: loki
    ports:
      - 3100:3100
      - 7946
      - 9095

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    command: "master"

    ports:
      - "9333:9333"

    volumes:
      - seaweedfs_master_data:/data

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume

    command: 'volume -mserver="seaweedfs-master:9333" -dir="/data"'

    depends_on:
      seaweedfs-master:
        condition: service_started
  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    expose:
      - 3200
      - 4317
      - 4318
    depends_on:
      mimir:
        condition: service_started

  mimir:
    image: grafana/mimir:3.0.5
    container_name: mimir
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml
    ports:
      - 9008:9008
      - 9009:9009

  prometheus:
    image: prom/prometheus:main-distroless
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      [
        "--web.enable-remote-write-receiver",
        "--config.file=/etc/prometheus/prometheus.yaml",
      ]
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  promtail:
    image: grafana/promtail:3.6
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./config/promtail/config.yaml:/etc/promtail/config.yaml
    command: ["-config.file=/etc/promtail/config.yaml"]

  grafana:
    image: grafana/grafana:12.4.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
      mimir:
        condition: service_started
      prometheus:
        condition: service_started

  otel:
    image: otel/opentelemetry-collector-contrib:nightly
    container_name: otel
    ports:
      - 4317:4317 # gRPC
      - 4318:4318 # HTTP
      - 8888:8888 # prometheus-collector
      - 8889:8889 # prometheus-exporter
      - 1888:1888 # pprof
      - 13133:13133 # Health
      - 55679:55679 # z-pages
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otelcol/config.yaml
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
      mimir:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started

volumes:
  seaweedfs_master_data:
  seaweedfs_volume_data:
