server:
  http_listen_port: 3200

distributor:
  receivers: 
    otlp: 
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 30m

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write: 
      - url: http://mimir:9090/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: s3
    s3:
      endpoint: garage:3900
      bucket: tempo
      access_key: ${GARAGE_ACCESS_KEY}
      secret_key: ${GARAGE_SECRET_KEY}
      insecure: true
    wal:
      path: /tmp/tempo/wal

overrides:
  metrics_generator_processors: [service-graphs, span-metrics]